name: Deploy Next.js to IIS Remotely

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
      SERVER: ${{ secrets.IIS_SERVER }}
      USER: ${{ secrets.IIS_USER }}
      PASSWORD: ${{ secrets.IIS_PASSWORD }}

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Build Next.js app
    - name: Build Next.js app
      run: npm run build

    # 5. Deploy to IIS remotely
    - name: Deploy to IIS via PowerShell Remoting
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"

        # Convert password to secure string and create credential object
        $secPassword = ConvertTo-SecureString $env:PASSWORD -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential ($env:USER, $secPassword)

        # Remote script block
        $scriptBlock = {
            param($sourcePath, $destinationPath, $appPool, $siteName)

            # Stop IIS App Pool and Website
            try { Stop-WebAppPool -Name $appPool -ErrorAction Stop; Write-Host "App Pool stopped." } catch { Write-Host $_ }
            try { Stop-Website -Name $siteName -ErrorAction Stop; Write-Host "Website stopped." } catch { Write-Host $_ }

            # Copy files (robocopy)
            robocopy $sourcePath "$destinationPath\.next" /E /MIR
            robocopy "$sourcePath\public" "$destinationPath\public" /E /MIR
            robocopy "$sourcePath\node_modules" "$destinationPath\node_modules" /E /MIR
            Copy-Item "$sourcePath\package.json" "$destinationPath\package.json" -Force

            if ($LASTEXITCODE -ge 8) { throw "File copy failed with exit code $LASTEXITCODE" }
            Write-Host "Files copied successfully."

            # Start IIS App Pool and Website
            try { Start-WebAppPool -Name $appPool -ErrorAction Stop; Write-Host "App Pool started." } catch { throw }
            try { Start-Website -Name $siteName -ErrorAction Stop; Write-Host "Website started." } catch { throw }
        }

        # Define parameters for remote execution
        $sourcePath = "${{ github.workspace }}"  # workspace of GitHub runner
        $destinationPath = "C:\inetpub\wwwroot\YourAppName"
        $appPool = "YourAppPoolName"
        $siteName = "YourSiteName"

        # Execute remotely on IIS server
        Invoke-Command -ComputerName $env:SERVER -Credential $cred -ScriptBlock $scriptBlock -ArgumentList $sourcePath, $destinationPath, $appPool, $siteName

    # 6. Post-deployment status
    - name: Post-deployment status
      if: always()
      shell: pwsh
      run: |
        if (${{ job.status }} -eq 'success') { Write-Host "Deployment succeeded ✅" } 
        else { Write-Host "Deployment failed ❌"; exit 1 }
